### ISSUE TITLE
READMEを作成する

### ISSUE THREAD

**Issue by akinari0919** [akinari0919/maji-info#1]
よろしくお願いします！

**Comment by akinari0919** [comment]
https://github.com/akinari0919/maji-info/commit/8ad901ecb146c5af70caa02a82422cb14cd7d1d5
https://github.com/akinari0919/maji-info/commit/4abb8710161801496caa80a1c1ec88434a078cae

概要の草案まで作成しました！
確認よろしくです！

---
## 🔹サービス概要🔹
### __🔻3行で__
過去にRUNTEQ生が<br>
Mattermostに投稿した有益な情報を<br>
定期的に紹介してくれるBotサービスです。

### __🔻メインターゲット__
- 新入RUNTEQ生

### __🔻ユーザーが抱える課題__
- おすすめのチャンネルが分からない
- 他のRUNTEQ生の有益な情報を知らないままになることがある

### __🔻解決方法__
定期的に有益情報が流れてくるチャンネルをつくることで、<br>
新たな学びやコミュニティ作りのきっかけにしてもらいます。

### __🔻実装予定の機能__
- MVP
  - ログイン機能（管理者投稿用）
  - 投稿CRUD機能
  - 投稿された情報のURLをMattermostの専用チャンネルに<br>
    定期的（毎日18時）に配信する
- MVP以降の拡張機能(想定)
  - RUNTEQ生限定で一般ユーザー登録・投稿
  - URL以外の情報(リアルな投稿の形)として配信
  - 管理者画面

### __🔻なぜこのサービスを作りたいのか？__
RUNTEQ生全員チャンネルフォローしていると有益情報が手に入りやすくなる反面、情報過多になるデメリットもありました。これからも増え続けるコミュニティに備え、情報整理の為と新しく入学されてくるRUNTEQ生にとっての情報収集のきっかけの場にしたいと考え開発することにしました。

### __🔻スケジュール__
- MVPリリース：4/17

<br>

## 🔹使用技術(予定)🔹
### __🔻バックエンド__
- Ruby
- Ruby on Rails

### __🔻Gem__
- sorcery
- pry-beybug
- rspec-rails
- factorybot
- capybara
- awesome print
- i18n
- rubocop

### __🔻フロント__
- HTML

### __🔻テスト__
- Rspec

### __🔻インフラ__
- Docker
- PostgreSQL
- Heroku

**Comment by akinari0919** [comment]
フロントですけど未だ書いてないですがTailwind使ってみませんか？
個人的に使ってみたくて、、

**Comment by Ryosuke-nakagawa** [comment]
README作成ありがとうございます。いいと思います！

Tailwind使ったことないので興味あります！
やってみましょ！

**Comment by akinari0919** [comment]
今日中に修正しておきます！

**Comment by akinari0919** [comment]
https://github.com/akinari0919/maji-info/commit/857416094b4996443c3f5f6524a6a2d5ec11006f

tailwind追記修正してます！
ついでに一部改行修正入れてます。
