### ISSUE TITLE
Postテーブルにカラム追加

### ISSUE THREAD

**Issue by Ryosuke-nakagawa** [akinari0919/maji-info#34]

**Comment by Ryosuke-nakagawa** [comment]
https://app.diagrams.net/#G1DuTKVJtGrHR0C29BCe1anMwWSt2IyTY4
[![Image from Gyazo](https://i.gyazo.com/9a3992981f3ce96c27ff77d14b19af12.png)](https://gyazo.com/9a3992981f3ce96c27ff77d14b19af12)

Postテーブルに
* url
* title
* contributor
を追加しようと思いますがカラム名などこれで問題ないですかね？

**Comment by akinari0919** [comment]
ありがとうございます！
タイトルってタグが入るんでしたっけ？？

**Comment by Ryosuke-nakagawa** [comment]
タイトルには題名が入って、
タグは別のイシューでタグテーブルを作成しようかと思っています！
参考：https://qiita.com/ki_87/items/a344ea566c88b10b950c

**Comment by akinari0919** [comment]
https://github.com/akinari0919/maji-info/issues/34#issuecomment-1106055477
了解です！題名って投稿する人が考えるってことで合ってましたか？🙏

**Comment by akinari0919** [comment]
あと、投稿済みかtrue/failseで判別するカラムは別のタイミングで入れます？

**Comment by Ryosuke-nakagawa** [comment]
> [#34 (comment)](https://github.com/akinari0919/maji-info/issues/34#issuecomment-1106055477) 了解です！題名って投稿する人が考えるってことで合ってましたか？🙏

そういうイメージです！

> あと、マタモに送信済みかtrue/failseで判別するカラムは別のタイミングで入れます？

別イシューでやろうと思います！
